/*
 * (C) Copyright 2006 Jean-Baptiste Note <jean-baptiste.note@m4x.org>
 * All rights reserved.
 */

#ifndef _SITES_V2_H
#define _SITES_V2_H

typedef enum _switch_type {
  SW_NONE = 0, SW_CLB,
  SW_TTERM, SW_LTERM, SW_BTERM, SW_RTERM,
  SW_TLTERM, SW_LTTERM, SW_LBTERM, SW_BLTERM,
  SW_BRTERM, SW_RBTERM, SW_RTTERM, SW_TRTERM,
  SW_TTERMBRAM, SW_BTERMBRAM,
  SW_TIOI, SW_LIOI, SW_BIOI, SW_RIOI,
  SW_TIOIBRAM, SW_BIOIBRAM,
  SW_BRAM, SW_BM,
  SW_TL, SW_BL, SW_BR, SW_TR,
  SW_M,
  SW_CLKT, SW_CLKB, SW_GCLKC, SW_GCLKH, SW_GCLKHBRAM,
  NR_SWITCH_TYPE,
} __attribute__((packed)) switch_type_t;

typedef enum _site_type {
  SITE_TYPE_NEUTRAL = 0,
  CLB,
  TTERM, LTERM, BTERM, RTERM,
  TLTERM = 6, LTTERM, LBTERM, BLTERM, BRTERM, RBTERM, RTTERM, TRTERM,
  TTERMBRAM = 14, BTERMBRAM,
  TIOI = 16, LIOI, BIOI, RIOI,
  TIOIBRAM = 20, BIOIBRAM,
  BRAM = 22, BM,
  TL = 24, BL, BR, TR,
  M = 28,
  CLKT = 29, CLKB, GCLKC, GCLKH, GCLKHBRAM,
  NR_SITE_TYPE,
} __attribute__((packed)) site_type_t;

#define SIMPLE_SITE(x) [x] = 1ULL << SW_ ## x
static const uint64_t sw_of_type[NR_SITE_TYPE] = {
  [SITE_TYPE_NEUTRAL] = 0,
  SIMPLE_SITE(CLB),
  SIMPLE_SITE(TTERM), SIMPLE_SITE(LTERM), SIMPLE_SITE(BTERM),
  SIMPLE_SITE(RTERM), SIMPLE_SITE(TLTERM), SIMPLE_SITE(LTTERM),
  SIMPLE_SITE(LBTERM), SIMPLE_SITE(BLTERM), SIMPLE_SITE(BRTERM),
  SIMPLE_SITE(RBTERM), SIMPLE_SITE(RTTERM), SIMPLE_SITE(TRTERM),
  SIMPLE_SITE(TTERMBRAM), SIMPLE_SITE(BTERMBRAM),
  SIMPLE_SITE(TIOI), SIMPLE_SITE(LIOI),
  SIMPLE_SITE(BIOI), SIMPLE_SITE(RIOI),
  SIMPLE_SITE(TIOIBRAM), SIMPLE_SITE(BIOIBRAM),
  SIMPLE_SITE(BRAM), SIMPLE_SITE(BM),
  SIMPLE_SITE(TL), SIMPLE_SITE(BL),
  SIMPLE_SITE(BR), SIMPLE_SITE(TR),
  SIMPLE_SITE(M),
  SIMPLE_SITE(CLKT), SIMPLE_SITE(CLKB),
  SIMPLE_SITE(GCLKC), SIMPLE_SITE(GCLKH),
  SIMPLE_SITE(GCLKHBRAM),
};
#undef SIMPLE_SITE

typedef enum _wire_direction {
  WIRE_DIRECTION_NEUTRAL = 0,
  N, WN, NW,
  W, WS, SW,
  S, SE, ES,
  E, EN, NE,
  DN, UP, // global clock
  NR_WIRE_DIRECTION,
} __attribute__((packed)) wire_direction_t;

typedef enum _wire_situation {
  WIRE_SITUATION_NEUTRAL = 0,
  BEG, A, B, MID, C, D, END,
  NR_WIRE_SITUATION,
} __attribute__((packed)) wire_situation_t;

typedef enum _wire_type {
  WIRE_TYPE_NEUTRAL = 0,
  DOUBLE, HEX,
  OMUX,
  BX, BY,
  BX_PINWIRE, BY_PINWIRE,
  CE, CIN,
  CLK,
  COUT,
  DX, DY,
  F1, F2, F3, F4,
  F1_PINWIRE, F2_PINWIRE, F3_PINWIRE, F4_PINWIRE,
  F5, FX, FXINA, FXINB,
  G1, G2, G3, G4,
  G1_PINWIRE, G2_PINWIRE, G3_PINWIRE, G4_PINWIRE,
  GCLK,
  // XXX might want to replace those 4 with one type + DIR
  GCLKC_GCLKB, GCLKC_GCLKL, GCLKC_GCLKR, GCLKC_GCLKT,
  GCLKH_GCLK_B,
  GCLKH_GCLK, // with dir DN and UP
  LH, LV,
  SHIFTIN, SHIFTOUT, SR,
  TBUF, TBUS,
  TI, TOUT, TS,
  VCC_PINWIRE,
  WF1_PINWIRE, WF2_PINWIRE, WF3_PINWIRE, WF4_PINWIRE,
  WG1_PINWIRE, WG2_PINWIRE, WG3_PINWIRE, WG4_PINWIRE,
  X, XB, XQ,
  Y, YB, YQ,
  NR_WIRE_TYPE,
} __attribute__((packed)) wire_type_t;

#endif /* _SITES_V2_H */
